### ISSUE TITLE
Could you provide the complete dataset?

### ISSUE THREAD

**Issue by 27182812** [gaojingsheng/LiveChat#2]
Hello, excellent work! I would like to conduct relevant research on this dataset. Could you provide the complete dataset?

**Comment by gaojingsheng** [comment]
Sorry for the lating of LiveChat, all of the processed dataset can be retrieved from here: https://github.com/gaojingsheng/LiveChat/blob/master/Dataset/README.md

**Comment by 27182812** [comment]
Thank you for your reply! And I'm curious about the character information in the basic_file.json. Currently it is anonymized, but the only character is not important for identification, is it convenient to provide a complete list of character information? This will be of great help to me and I will explain the help of your work in my research. You can also send it to me via email.

**Comment by gaojingsheng** [comment]
Sure, but in our preliminary experiments, we actually found that the different dimensions of features annotated in LiveChat had no significant impact on the effectiveness of responses. Therefore, we didn't present this part of the results. We only released anonymized results, partly to protect privacy and partly because the results were not significant. You can contact me via email, and I will send you the mapping table. My email address is [gaojingsheng@sjtu.edu.cn]
